---
title: "Labour market integration"
format: html
editor: visual
---

## Labour market indicators 

The indicators below are the ones to be used for integration model from a gender perspective to understand the differences.

Pakistan 2024 dataset will be used exemplary.

```{r disaggregation, echo=FALSE}


table(FDS_PAK_2024_RA_adult$variables$HH_02_RA)
table(FDS_PAK_2024_RA_adult$variables$disability_RA)
table(FDS_PAK_2024_RA_adult$variables$Intro_07)

 
```

```{r labour market, echo=FALSE}


##Employment Indicators


table(FDS_PAK_2024_RA_adult$variables$labour_force)


## Labour force participation rate

PAK_RA_adult <- PAK_RA_adult %>%
  mutate(unpaid_work = case_when(
    unemployed == 0 & employed == 0 & EMP30 %in% c(2,5,6) ~ 1,  
    TRUE ~ 0
  )) |>
  mutate(no_job_want = case_when(
    unemployed == 0 & employed == 0 & EMP27 == 2 ~ 1,  
    TRUE ~ 0
  )) |>
  mutate(no_job_search = case_when(
    unemployed == 0 & employed == 0 &  EMP27 == 1 & EMP25a == 2 & EMP25aa == 2 ~ 1,  
    TRUE ~ 0
  )) |>
  mutate(no_job_availability = case_when(
    unemployed == 0 & employed == 0 &  EMP27 == 1 & EMP25a == 1 & EMP25aa == 1 & EMP29 == 2 ~ 1,  
    TRUE ~ 0
  )) |>
  mutate(outside_lab_force_potential = case_when(EMP27 == 1 & EMP29 == 1 & EMP25a == 2 & EMP25aa == 2 ~ 1, # Available for a job but not searching
                                                 TRUE ~ 0)) |>
  mutate(outside_lab_force_no_potential = case_when(unemployed == 0 & employed == 0 & outside_lab_force_potential == 0 ~ 1,
                                                    TRUE ~ 0)) |>
  mutate(labour_force_status = case_when(
    employed == 1 ~ 1,
    unemployed == 1 ~ 2,
    outside_lab_force_potential == 1 ~ 3,
    outside_lab_force_no_potential == 1 ~ 4,
    TRUE ~ NA_real_
  )) |>
  mutate(labour_force_status = labelled(labour_force_status,
                                        labels = c("Employed" = 1,
                                                   "Unemployed" = 2,
                                                   "Outside labour force - unavailable - potential labour force (available but not looking for a job)" = 3,
                                                   "Outside labour force - unavailable" = 4)))

FDS_PAK_2024_RA_adult <- PAK_RA_adult %>%
  as_survey_design(
    strata = samp_strat,           # Specify the column with cluster IDs
    weights = wgh_samp_pop_restr_resp, # Specify the column with survey weights
    nest = TRUE              # Use TRUE if PSUs are nested within clusters (optional, based on your survey design)
  )

table(FDS_PAK_2024_RA_adult$variables$labour_force_status) # Use as binary variable 


##Now check with the main activity for those in the labour force


# Type of unpaid work

hhwork_G <- FDS_PAK_2024_RA_adult %>%
  filter(EMP30 %in% c(2,5,6), !is.na(EMP30)) %>%
  mutate(hhwork = case_when(EMP30 == 2 ~ 1,
                            EMP30 != 2 ~ 0)) %>%
  filter(!is.na(HH_02_RA), !is.na(Intro_07)) %>%     # Exclude if pop groups is NA
  group_by(Intro_07, HH_02_RA) %>%      # Show results disaggregated by pop groups
  summarise(
    var_name = "Household/care work",
    num_obs_uw = n(),
    denominator = survey_total(),
    mean_value = survey_mean(hhwork, vartype = c("ci", "se"), na.rm = TRUE)
  )

farming_G <- FDS_PAK_2024_RA_adult %>%
  filter(EMP30 %in% c(2,5,6), !is.na(EMP30)) %>%
  mutate(farming = case_when(EMP30 == 5 ~ 1,
                             EMP30 != 5 ~ 0)) %>%
  filter(!is.na(HH_02_RA), !is.na(Intro_07)) %>%     # Exclude if pop groups is NA
  group_by(Intro_07, HH_02_RA) %>%      # Show results disaggregated by pop groups
  summarise(
    var_name = "Farming",
    num_obs_uw = n(),
    denominator = survey_total(),
    mean_value = survey_mean(farming, vartype = c("ci", "se"), na.rm = TRUE)
  )

volunteering_G <- FDS_PAK_2024_RA_adult %>%
  filter(EMP30 %in% c(2,5,6), !is.na(EMP30)) %>%
  mutate(volunteering = case_when(EMP30 == 6 ~ 1,
                                  EMP30 != 6 ~ 0)) %>%
  filter(!is.na(HH_02_RA), !is.na(Intro_07)) %>%     # Exclude if pop groups is NA
  group_by(Intro_07, HH_02_RA) %>%      # Show results disaggregated by pop groups
  summarise(
    var_name = "Volunteering",
    num_obs_uw = n(),
    denominator = survey_total(),
    mean_value = survey_mean(volunteering, vartype = c("ci", "se"), na.rm = TRUE)
  )

# Bind the dataframes together
unpaid_combined_G <- bind_rows(hhwork_G, farming_G, volunteering_G)

unpaid_combined_G <- unpaid_combined_G  %>%
  group_by(Intro_07, HH_02_RA) %>%
  arrange(desc(var_name)) %>%
  mutate(cumulative_sum = cumsum(mean_value) - (mean_value / 2))  |>
  mutate(HH_02_RA = labelled::to_factor(HH_02_RA))




```

```{r education, echo=FALSE}

#Education from HHroster

table(FDS_PAK_2024_HHroster$variables$HH_Educ18) #Highest level of education

#merge with rosterposition and uuid

table(PAK_HHroster$rosterposition)
table(PAK_RA_adult$rosterposition)


PAK_RA_adult <- PAK_RA_adult %>%
  mutate(rosterposition = as.numeric(rosterposition)) %>%
  left_join(
    PAK_HHroster %>%
      mutate(rosterposition = as.numeric(rosterposition)) %>%
      select(uuid, rosterposition, HH_Educ18, HH_Educ23, HH_Educ07),
    by = c("uuid", "rosterposition")
  )

```

```{r skills, echo=FALSE}


#Check tables

##Skills -1 Yes 2 No

table(FDS_PAK_2024_RA_adult$variables$Exp01a) #Caring for children
table(FDS_PAK_2024_RA_adult$variables$Exp01c) #Caring for sick or disabled people
table(FDS_PAK_2024_RA_adult$variables$Exp01d) #Making/mending clothing
table(FDS_PAK_2024_RA_adult$variables$Exp01e) #Preparing meals / baking
table(FDS_PAK_2024_RA_adult$variables$Exp01f) #Cultivating crops
table(FDS_PAK_2024_RA_adult$variables$Exp01g) #Taking care of livestock
table(FDS_PAK_2024_RA_adult$variables$Exp01h) #Fishing
table(FDS_PAK_2024_RA_adult$variables$Exp01i) #Handicraft activities
table(FDS_PAK_2024_RA_adult$variables$Exp01j) #Selling or trading products
table(FDS_PAK_2024_RA_adult$variables$Exp01k) #Making furniture
table(FDS_PAK_2024_RA_adult$variables$Exp01l) #House construction
table(FDS_PAK_2024_RA_adult$variables$Exp01m) #Coaching/teaching
table(FDS_PAK_2024_RA_adult$variables$Exp01n) #Photography/film-making
table(FDS_PAK_2024_RA_adult$variables$Exp01o) #Hairdressing/aesthetic care

```

```{r runbusiness, echo=FALSE}


##HAVE YOU EVER RUN A BUSINESS?

table(FDS_PAK_2024_RA_adult$variables$Exp03) #Ever run a business



```

```{r softskills, echo=FALSE}

###Reading/writing skills

table(FDS_PAK_2024_RA_adult$variables$Skill01a) #Can you read following items easily 
#Phone messages on platforms like WhatsApp,Messenger,Instagram
#1. Easily
#2. Withsomedifficulty
#3. Withlotsofdifficulty
#4. Notatall


table(FDS_PAK_2024_RA_adult$variables$Skills06b) #Calculateprices 
table(FDS_PAK_2024_RA_adult$variables$Skills06c) #Performanyothermultiplicationordivision 
table(FDS_PAK_2024_RA_adult$variables$Skills06d) #useorcalculatefractions,decimalsorpercentages


table(FDS_PAK_2024_RA_adult$variables$Skills38a) #use mobile phone
table(FDS_PAK_2024_RA_adult$variables$Skills38b) #use smart phone
table(FDS_PAK_2024_RA_adult$variables$Skills38c) #a tablet
table(FDS_PAK_2024_RA_adult$variables$Skills39) #used computer in the past 3 months
table(FDS_PAK_2024_RA_adult$variables$Skills41a) #send receive emails
table(FDS_PAK_2024_RA_adult$variables$Skills41b) #making internet/video calls
table(FDS_PAK_2024_RA_adult$variables$Skills41c) #finding information on internet
table(FDS_PAK_2024_RA_adult$variables$Skills41d) #learning/studying online


table(FDS_PAK_2024_RA_adult$variables$Skills42a) #driving license to drive a car
table(FDS_PAK_2024_RA_adult$variables$Skills42b) #driving license to drive a truck

#add job search sction
table(FDS_ZAM_2025_RA_adult$variables$PL01_10) #driving license to drive a truck

```

```{r legalrighttowork, echo=FALSE}

##To your knowledge, do you have the right to work legally in Pakistan?

table(FDS_PAK_2024_RA_adult$variables$JobLegal1) #to your knowledge d you have a right to work?


```

```{r ownchildren, echo=FALSE}

# Not possible to calculate as randomly selected adult is not always the spouse -

#Women with children under 2
#Women with children under 5

##We can instead use the question ->Did you/${membName} give birth to a child who was bornaliveinthepast2years?

table(PAK_HHroster$HH_27)


table(FDS_PAK_2024_HHroster$variables$HH_27) #Giver birth to a live child in the past 2 years

#merge with rosterposition and uuid

table(PAK_HHroster$rosterposition)
table(PAK_RA_adult$rosterposition)


PAK_RA_adult <- PAK_RA_adult %>%
  mutate(rosterposition = as.numeric(rosterposition)) %>%
  left_join(
    PAK_HHroster %>%
      mutate(rosterposition = as.numeric(rosterposition)) %>%
      select(uuid, rosterposition, HH_27),
    by = c("uuid", "rosterposition")
  )


table(PAK_RA_adult$HH_27)

```

```{r}

#Ownership of a bank account or any financial account

#We can use the RBM indicator which is Proportion of people with an account at a bank or other financial institution or with a mobile-money provider
table(PAK_RA_adult$RBM21301)
  

```

```{r}

#Depression rates
####Subjective well being

##Suggestions on depression

#The Total Score indicates the Depression Severity: 
#  0-4 - Minimal depression
#5-9 - Mild depression
#10-14 - Moderate depression
#15-19 - Moderately severe depression
#20-27 - Severe depression


# PHQ9 <- PHQ9 %>%
#   mutate(across(starts_with("MH01_"), 
#                 ~ recode(as_factor(.), 
#                          "not at all" = 0, 
#                          "several days" = 1, 
#                          "more than half the days" = 2, 
#                          "nearly every day" = 3, 
#                          "refused to answer" = NA_real_, 
#                          .default = NA_real_) %>%
#                   as.numeric(),
#                 .names = "new_{col}"))

PAK_RA_adult <- PAK_RA_adult %>%
  mutate(across(starts_with("MH01_"), 
                ~ ifelse(. == 99, NA_real_, as.numeric(.)), 
                .names = "new_{.col}"))

head(PAK_RA_adult %>% select(starts_with("MH01"), starts_with("new_MH01"))) # View the output




PAK_RA_adult <- PAK_RA_adult %>%
  mutate(PHQ9 = new_MH01_1 + new_MH01_2 + new_MH01_3 + new_MH01_4 +
           new_MH01_5 + new_MH01_6 + new_MH01_7 + new_MH01_8 + new_MH01_9)


# Create the depression variable
PAK_RA_adult <- PAK_RA_adult %>%
  mutate(depression = ifelse(PHQ9 >= 10, 1, 0)) #1=depressed, 0=not depressed


table(PAK_RA_adult$depression)
```

```{r}
#Decision-making section - check if we can add

#Indicator as here:

#1 always respondent
#2 usually respondent
#3 respondent and spouse equally
#4 usually spouse
#5 always spouse
#6 always or usually other person in the household
#7 always or usually someone else not living in the household
#97 not applicable

table(PAK_RA_adult$MD01_1) #Routine purchase for the HH
table(PAK_RA_adult$MD01_2) #Occasional expensive purchase
table(PAK_RA_adult$MD01_3) #time you spend in paid work
table(PAK_RA_adult$MD01_4) #time spouse spend in paid work
table(PAK_RA_adult$MD01_5) #the way children raised
table(PAK_RA_adult$MD01_6) #your family social life and leisure
table(PAK_RA_adult$MD01_7) #who you spend time with
table(PAK_RA_adult$MD01_8) #who your spouse spend time with
table(PAK_RA_adult$MD01_9) #having children

```

```{r}
#If any of the languages in the host country is spoken 

#it;s hard to know in bordering countries - which languages are spoken already in the region - so this will be discarded


```

```{r}
#Job search barriers + lack of reading, computer literacy + legal literacy +
#1 yes 2 no

table(PAK_RA_adult$JobSearch11) #lack of reading/ writing skills
table(PAK_RA_adult$JobSearch12) #lack of computer/digital skills
table(PAK_RA_adult$JobSearch13) #lack of legal documents
table(PAK_RA_adult$JobSearch14) #discrimination in the labour market


```

```{r}
#Discrimination
#1 almost everyday
#2 at least once a week
#3 a few times a month
#4 a few times a year
#5 once a year
#6 never
#7 i dont know
table(PAK_RA_adult$DI01_01) #treated with less politeness
table(PAK_RA_adult$DI01_02) #treated with less respect
table(PAK_RA_adult$DI01_03) #receive poorer service in restaurants
table(PAK_RA_adult$DI01_04) #people think that you are not smart
table(PAK_RA_adult$DI01_05) #people act as if they are afraid of you
table(PAK_RA_adult$DI01_06) #people act as if you are dishonest
table(PAK_RA_adult$DI01_07) #people act as if they are better than you
table(PAK_RA_adult$DI01_08) #you are called names or insulted
table(PAK_RA_adult$DI01_09) #threatened or harrassed

```

```{r}
#Documentation linked to gender

##work permits?
##There is info on frmal employment but many skip logic - perhaps better to skip 


```

```{r}
#Ownership of a mobile phone 
#Its an SDG indicator

table(PAK_RA_adult$C050b01) #when an individual has a mobile phone with active sim card

```

```{r}
#Safety feeling + if you cannot move in the evening.
#Proportion of population that feel safe walking alone around the area they live after dark**

table(PAK_RA_adult$FS01) #feeling safe walking alone in the dark

#Very safe
#Fairly safe
#bit unsafe
#very unsafe
#i never walk alone
#dont know

table(PAK_RA_adult$C160105)


```

```{r}
#Time spent on domestic work

#1 Always respondent 
#2 usually repondent
#3respondent and spouse equally
#4 usually spouse
#5 always spouse
#6 always or usually other person in the household
#7always or usually someone else not living in the household
#97 not applicable

table(PAK_RA_adult$DW01_6) # Make repairs to your home, furniture, vehicle and applicances
table(PAK_RA_adult$DW01_2) # Do the laundry and wash cloth
table(PAK_RA_adult$DW01_4) #shop for the household
table(PAK_RA_adult$DW01_3) #cook
table(PAK_RA_adult$DW01_7) #collect water for your household
table(PAK_RA_adult$DW01_8) #collect firewood for the household
table(PAK_RA_adult$DW01_10) #take care of elderly or disabled
table(PAK_RA_adult$DW01_9) #take care of children
table(PAK_RA_adult$DW01_1) #clean the house
table(PAK_RA_adult$DW01_5) #manage household finances
```

```{r}
#Safety at work ( from protection section)
```

```{r}
#Documentation -that is any valid ID document? Also, work permits 
```

```{r}
#Trainings -> check indicator EducR16

##ANY TRAINING in the country of origin or host country

#ANY training that is not part of educational system

table(PAK_RA_adult$EducR13)
```

```{r}

#Information about job

#In the last 30 days did you look information about job opportunities

table(PAK_RA_adult$INFO00_3)
```
